### ISSUE TITLE
Integración de Google Sign-In al proyecto.

### ISSUE THREAD

**Issue by lcs1001** [lcs1001/gestion-aulas-informatica#55]

**Comment by lcs1001** [comment]
Para ello voy a seguir el [tutorial de Vaadin para usar OAuth 2 y Google Sign-In](https://vaadin.com/learn/tutorials/google-login).

**Comment by lcs1001** [comment]
Al acceder a la app aparece el link para acceder con Google:
![image](https://user-images.githubusercontent.com/44766371/85707864-e2f8a980-b6e3-11ea-87e6-9a021371466c.png)

Como está indicado en la clase "LoginScreen" redirige a "http://localhost:8080/oauth2/authorization/google", que no está entre las rutas definidas en el proyecto por lo que aparece una lista con las disponibles:
![image](https://user-images.githubusercontent.com/44766371/85708077-189d9280-b6e4-11ea-861c-41e27743bf79.png)

En la que he configurado la sesión de usuario, tal y como hacen en el tutorial en el MainView, es en ConsultaReservasView (la que aparece como "<root>"), pero si accedemos a ella aparece que se ha lanzado una excepción :
![image](https://user-images.githubusercontent.com/44766371/85708307-53072f80-b6e4-11ea-93eb-4d040a405b3a.png)

Desde eclipse se puede acceder a la línea de código que ha producido dicha excepción, en este caso en la clase UserSession:
![image](https://user-images.githubusercontent.com/44766371/85708468-7df18380-b6e4-11ea-9ecf-9d30d0ff196e.png)
![image](https://user-images.githubusercontent.com/44766371/85708446-75994880-b6e4-11ea-9b8f-7b8a36b65d5a.png)

**Comment by lcs1001** [comment]
Este excepción se ha producido después de acceder la primera vez exitosamente tras haberlo configurado, de forma que aparecía la imagen de la cuenta de Google y el nombre de la cuenta, pulsar en el link "logout" que aparecía y tratar de acceder de nuevo desde la ventana de login.

En ninguno de los casos me ha pedido elegir la cuenta con la que quiero acceder, ya que en alguna de las pruebas de configuración la elegí y se queda guardada, sin que haya forma de eliminarla para poder pedirla otra vez.

**Comment by lcs1001** [comment]
A partir de Vaadin 15, en la carpeta "frontend" del proyecto se encuentra el "index.html", por lo que se puede modificar e incluir elementos directamente.

**Comment by lcs1001** [comment]
Una posible solución/ alternativa es utilizar la autenticación con [Firebase](https://firebase.google.com/?hl=es), la cual permite agregar Google Sign-In.

**Comment by lcs1001** [comment]
Desde Vaadin 15 el archivo "index.html" está incluido en el proyecto, por lo que se pueden incluir directamente en él las líneas necesarias.

**Comment by lcs1001** [comment]
Incluyendo lo indicado en el [tutorial de Google Sign-In para Web](https://developers.google.com/identity/sign-in/web) en el index.html se muestra en la página inicial el botón de acceso y el enlace para cerrar la sesión:
![image](https://user-images.githubusercontent.com/44766371/86293796-a0f3ca00-bbf3-11ea-9759-46fba5b27615.png)
Y, como se indica en el código, se muestra en la consola del inspector los datos del usuario logeado y el mensaje de "salida" cuando pinchamos en "Sign out":
![image](https://user-images.githubusercontent.com/44766371/86293858-bf59c580-bbf3-11ea-872a-1a0158170dcb.png)

**Comment by lcs1001** [comment]
Ahora hay que conseguir pasar el "ID Token" que identifica al usuario logeado al backend (al servidor) para poder tratarlo.

**Comment by jmaudes** [comment]
Perdona Lisa

Ayer estuve missing porque estaba impartiendo un curso toda la tarde y vine
reventado las 9;30

Veo que has encontrado una salida. Si al final tienes que usar Firebase,
hay que venderlo como un plus (otra tecnologia que has probado). Habra que
hacer hincapie en lo inestable que es Vaadin, que sigin te funcionaba a
principiode proyecto con Vaadin ¿x?, y que al tener que cambiar a Vaadin
¿x+1? por ¿ya no me acuerdo? has tenido que investigar y al final has
encontrado esa solucion de Firebase que tiene las ventajas x,y,z

Saludos

Jesus

**Comment by lcs1001** [comment]
Han sacado un nuevo componente de [Google Sign In compatible con Vaadin 14+](https://vaadin.com/directory/component/google-sign-in-v14) (a partir de la versión 14 de Vaadin).

Para usarlo simplemente hay que añadir la dependencia del componente (y si no está añadido el repositorio de addons de Vaadin) como indica:
![image](https://user-images.githubusercontent.com/44766371/86487108-8a698200-bd5d-11ea-9f33-208ab5f1044c.png)
![image](https://user-images.githubusercontent.com/44766371/86487128-99e8cb00-bd5d-11ea-8f06-d52d762dbc43.png)
![image](https://user-images.githubusercontent.com/44766371/86487154-a79e5080-bd5d-11ea-8806-34e9e9a94fdc.png)

Luego, como indica el autor en su GitHub para usarlo simplemente hay que añadir las siguientes líneas (indicando el ID de cliente Google creado anteriormente):
![image](https://user-images.githubusercontent.com/44766371/86487375-2b583d00-bd5e-11ea-9162-cb201e449f24.png)

**Comment by lcs1001** [comment]
Al ejecutar la app salta una excepción de que no encuentra la clase "UserLoginEvent" (la encargada de recuperar la información del usuario):
![image](https://user-images.githubusercontent.com/44766371/86487429-5478cd80-bd5e-11ea-949e-0a182e3f0afb.png)

**Comment by lcs1001** [comment]
Optaré por aplazar (o incluso descartar) la integración de Google Sign-In y de Google Calendar (#54) hasta obtener una respuesta sobre la solución de este fallo (por parte del autor, del equipo de Vaadin o de alguien) en el apartado de discusiones del enlace del componente.
